config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  get 'signup' => 'users#new'

  get 'sessions/new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get 'home' => 'microposts#home'

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        The form contains <%= pluralize(object.errors.count, "error") %>.
      </div>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
      <%= render @feed_items %>
    </ol>
    <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost, html: {multipart: true} do |f| %>
    <div class="field">
      <%= f.text_area :content, placeholder: "What's going on?" %>
      <div class="wrap-pictureupload">
        <div class="pictureupload"><p id="picturename">Add an image</p>
          <%= f.file_field :picture,
                           accept: 'image/jpeg,image/gif,image/png',
                           onchange: "getName(this.value)" %>
        </div>
      </div>
      <%= f.submit "Post", class: "button post-button" %>
      <span class="counter">140</span>
    </div>
    <%= render 'shared/error_messages', object: f.object %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <span>|</span>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
  <h2><%= "#{@user.microposts.count} fablebeats" %></h2>

</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 100), current_user %>
<h1><%= link_to "@#{current_user.nickname}", current_user %></h1>