config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  get 'signup' => 'users#new'

  get 'sessions/new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get 'home' => 'microposts#home'

end

app/views/pages/about.html.erb
<% provide(:title, "About") %>
<div class="about_pic">
  <!--section of image--->
  <div class="inform">
    <div class="header-main">
      <h1>Stories move the future</h1>
      <p>Inspire your friends to new feats</p>
    </div>
  </div>
</div>

<div class="jumbotron">
  <h2>Get started</h2>
  <p>Friends will see your discoveries<br>
    Freeze the moment and share it right now!</p>
  <% unless logged_in? %>
    <%= link_to "Sign up", signup_path, { :class => "button", :role => "button" } %>
      <% else %>
      <%= link_to "Go to profile", current_user, { :class => "button", :role => "button" } %>
  <% end %>
</div>

app/views/pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="contact-background">
    <div class="contact-info">
      <div class="circular"></div>
      <h1>Stanislav Pavlovitsky</h1>
      <h2>web developer, coffee destroyer</h2>
      <div class="soc-icons">
        <ul>
          <li>
            <a href="https://www.facebook.com/s.pavlovitsky"><%= image_tag "fb.png" %></a>
          </li>
          <li>
            <a href="https://www.linkedin.com/profile/view?id=305371552"><%= image_tag "li.png" %></a>
          </li>
          <li>
            <a href="https://plus.google.com/102812632047940656860/posts"><%= image_tag "gplus.png" %></a>
          </li>
        </ul>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
<% provide(:title, "Welcome") %>
<div class="first-picture">
  <div class="container-fluid">
    <div class="row">
      <% flash.each do |message_type, message| %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12">
        <h1 class="hidden-xs">Fablebeat</h1>
        <h1 class="visible-xs">Fablebeat</h1>
        <% unless logged_in? %>
            <div class="wrap-form">
              <%= form_for :session, url: login_url, method: :post,
                           html: {class: "for_login"} do |f| %>
                  <%= f.text_field :email_nickname,
                                   class: 'form-control',
                                   placeholder: 'Email or username' %>
                  <%= f.password_field :password, class: 'form-control',
                                       placeholder: 'Password' %>
                  <%= f.submit "Log in", class: "button" %>
                  <%= link_to "Sign up!", signup_path, method: :get, class: "button", form_class: "signup" %>
                  <div class=checkbox-inline>
                    <%= f.label :remember_me, class: "checkbox inline" do %>
                        <%= f.check_box :remember_me %>
                        <span>Remember me</span>
                        <%= link_to "(forgot password)", new_password_reset_path %>
                    <% end %>
                  </div>
              <% end %>
            </div>
            </div>
        <% end %> <!-- end of forms for non-logged user-->
        </div>
  </div>
</div>
</div>
<div class="jumbotron">
  <h2>Open yourself to the world</h2>

  <p>Share your emotions in text & photos</p>

  <div class="button_div">
    <a href="<%= about_path %>"
       class="button">Learn more</a>
  </div>
</div>
<div class="second-picture">
</div>