config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'

  get 'password_resets/edit'

  root 'pages#home'
  get 'about' => 'pages#about'
  get 'contact' => 'pages#contact'

  get 'signup' => 'users#new'

  get 'sessions/new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  get 'home' => 'microposts#home'

end

app/views/layouts/_footer.html.erb
<footer>
  <ul>
    <li>
      <figure>
        <%= link_to about_path do %>
        <%= image_tag 'footer_about.png', alt: 'about' %>
            <figcaption>About</figcaption>
            <% end %>
      </figure>
    </li>
    <li>
      <figure>
        <%= link_to contact_path do %>
            <%= image_tag 'footer_contact.png', alt: 'contact' %>
            <figcaption>Contact</figcaption>
        <% end %>
      </figure>
    </li>
    <li>
      <figure>
        <%= link_to '#' do %>
            <%= image_tag 'footer_portfolio.png', alt: 'portfolio' %>
            <figcaption>Portfolio</figcaption>
        <% end %>
      </figure>
    </li>
  </ul>
</footer>

app/views/layouts/_menu.html.erb
<!--Toggled menu-->
<nav class="menu">
  <!-- Menu icon -->
  <div class="icon-close">
    <i class="fa fa-times fa-2x"></i>
  </div>
  <!-- Menu -->
  <ul>
    <% if logged_in? %>
        <li>
          <%= link_to "Post & Read", home_path %>
        </li>
    <li>
      <%= link_to "Profile", current_user %>
    </li>
    <% end %>
    <li>
      <%= link_to "About", about_path %>
    </li>
    <li>
      <%= link_to "Home", root_path %>
    </li>
    <li>
      <%= link_to "Contact", contact_path %>
    </li>
    <% if logged_in? %>
        <li>
          <%= link_to "Log out", logout_path, method: :delete %>
        </li>
    <% end %>
  </ul>
</nav>
<!-- Main body -->
<div class="icon-menu">
  <i class="fa fa-bars fa-2x"></i>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Fablebeat", root_url, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
      <li><%= link_to "Post & Read", home_path,
                      class: (current_page?(home_path) ? "active-item" : "") %></li>
          <li><%= link_to "Profile", current_user,
                          class: (current_page?(current_user) ? "active-item" : "") %></li>
          <li><%= link_to "Users", users_path,
                          class: (current_page?(users_path) ? "active-item" : "") %></li>
      <% end %>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
               role="button" aria-haspopup="true" aria-expanded="false">Account
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Log out", {:controller => :sessions,
                                          :action => :destroy}, {:method => :delete} %></li>
            </ul>
          </li>
      <% end %>
      <% unless logged_in? %>
          <li><%= link_to "Log in", root_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag '//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.scss' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto:400,700,300' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<%= render 'layouts/menu' %>
<!-- Your content -->
<%= yield %>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<%= javascript_include_tag 'jquery-2.1.4.min.js', 'data-turbolinks-track' => true %>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/application_users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag 'application_users', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto:400,700,300' %>
  <%= javascript_include_tag 'application_users', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
  <![endif]-->
</head>
<body>
<div class="container-fluid">
  <%= render 'layouts/nav' %>
  <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
  <% end %>
  <!-- Your content -->
  <%= yield %>
</div>
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<%= javascript_include_tag 'jquery-2.1.4.min.js', 'data-turbolinks-track' => true %>
<%= render 'layouts/footer' %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>